### PR TITLE
Fix integration testing, add to CI

### PR DESCRIPTION
**Pull request by paulzzy**
- Run tests with standalone integration.sh
- Integration testing workflow now in ci.yml instead of nightly.yml

### CODE REVIEW

**Review by ryukinix — APPROVED** [review]

**Comment by paulzzy** [comment]
I updated all distro links, so downloading ISOs shouldn't be a problem. However, most distros (except TinyCore) have outdated boot info that causes the tests to fail. I'll leave that as a TODO, since the integration testing logic is now fixed and only config info is wrong.

**Comment by rminnich** [comment]
what should we do about the failures? merge anyway?

**Comment by rminnich** [comment]
oh I read your comment. Suggestion: add a map called broken, and add these to it, and VERY LOUDLY log that they are being skipped? If you're out of time, I'll do that.

**Comment by paulzzy** [comment]
That's a good suggestion! I am out of time, so I would greatly appreciate if you could implement it.

**Review by rminnich — APPROVED** [review]

**Pull request merged**
