### PR TITLE
add run-webboot.sh script to launch QEMU for webboot

### PR DESCRIPTION
**Pull request by orangecms**

### CODE REVIEW

**Comment by orangecms** [comment]
Why...?
```
2020/01/29 01:22:29 error building: error building go package in "/home/vsts/work/1/s/gopath/src/github.com/u-root/u-root/bb": # github.com/u-root/webboot/pkg/mountkexec
../../webboot/pkg/mountkexec/mountkexec.go:67:27: cannot use kernel (type *os.File) as type string in argument to multiboot.Probe
, exit status 2```

The code is untouched... :thinking:

**Comment by bjakobson** [comment]
the reason is because I added kernel type *os.Open, because a change in u-root happened that caused multiboot.probe to not take in a string. it worked for me, even using the command, so not sure why it wouldn't wok for you

**Comment by orangecms** [comment]
Yea until right now because u-root got a ton of reverts. -.-

**Comment by bjakobson** [comment]
let me see something, ill check

**Comment by orangecms** [comment]
We should fix this repo to not just YOLO use the master branch of u-root, however that works with Golang. You'll never know what you get otherwise.

**Comment by bjakobson** [comment]
ok, it doesn't work if I don't do the change. Let me have you do something: run this: `go run buildimage.go` inside webboot, and if you get an error, let me know

**Comment by bjakobson** [comment]
im curious about something, Azure is using go1.12, i wonder if this varies between versions

**Comment by bjakobson** [comment]
i found the error, will fix in a sec

**Pull request merged**
