### PR TITLE
Automatically download and compile wpa_supplicant

### PR DESCRIPTION
**Pull request by rjoleary**
To download and build your own wpa_supplicant, use:

	go run . --wpa-version=2.9

For me, this works for 2.7, 2.8 and 2.9.

Signed-off-by: Ryan O'Leary <ryanoleary@google.com>

### CODE REVIEW

**Comment by rminnich** [comment]
What problem does this solve?

**Comment by rminnich** [comment]
While I realize this builds, you're just substituting one unknown for another, so I'm still not sure of the value. Does this "build from source" come with a corresponding increase in understanding of what is going on?

**Comment by rjoleary** [comment]
Let's solve the other problem first.

This solves a different problem from what you're probably thinking. It solves the problem of different people are using different versions of wpa_supplicant.

**Review by rminnich — APPROVED** [review]

**Comment by rjoleary** [comment]
> Let's solve the other problem first.
> 
> This solves a different problem from what you're probably thinking. It solves the problem of different people are using different versions of wpa_supplicant.

This change is basically a no-op unless you set `--wpa-supplicant=2.7`, so it is safe to submit.

**Comment by rjoleary** [comment]
For some reason github actions is not happy: `Error: fatal: unable to access 'https://github.com/u-root/webboot/': The requested URL returned error: 500`

**Comment by rjoleary** [comment]
> For some reason github actions is not happy: `Error: fatal: unable to access 'https://github.com/u-root/webboot/': The requested URL returned error: 500`

GitHub is happy again. :)

**Review by rminnich — DISMISSED** [review]

**Review by rminnich — APPROVED** [review]

**Pull request merged**
